export const PLAYER_STOPPED = "PLAYER_STOPPED";
export const PLAYER_PAUSED = "PLAYER_PAUSED";
export const PLAYER_PLAYING = "PLAYER_PLAYING";
export const PLAYER_PREV = "PLAYER_PREV";
export const PLAYER_NEXT = "PLAYER_NEXT";

export const SET_SONG = 'SET_SONG';

export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SET_STORAGE = 'AUTHENTICATE_SET_STORAGE';

export const RECIEVE_SONGS = 'RECIEVE_SONGS';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const REQUEST_SONGS_FAILURE = 'REQUEST_SONGS_FAILURE';


export const clientID = '464566824c0ae5e54730991f549df552';
export const redirect = 'http://localhost:3000';
export const auth_url = `https://soundcloud.com/connect?client_id=${clientID}&response_type=code_and_token&scope=non-expiring&redirect_uri=${redirect}`;


export const defaultSongs = [
	{
	artwork_url: "https://i1.sndcdn.com/artworks-000125950621-h0ql5v-large.jpg",
	comment_count: 3,
	commentable: true,
	description: "",
	download_count: 0,
	downloadable: false,
	embeddable_by: "all",
	favoritings_count: 321,
	genre: "DFA",
	isrc: null,
	label_id: null,
	label_name: null,
	license: "all-rights-reserved",
	original_content_size: 23565293,
	original_format: "mp3",
	playback_count: 11167,
	purchase_title: null,
	purchase_url: null,
	release: null,
	release_day: null,
	release_month: null,
	release_year: null,
	reposts_count: 27,
	state: "finished",
	streamable: true,
	tag_list: "",
	track_type: null,
	user: {
	avatar_url: "https://i1.sndcdn.com/avatars-000154063588-09fh4i-large.jpg",
	id: 1520490,
	kind: "user",
	permalink_url: "http://soundcloud.com/dfa-records",
	uri: "https://api.soundcloud.com/users/1520490",
	username: "DFA Records",
	permalink: "dfa-records",
	last_modified: "2015/08/17 15:49:27 +0000"
	},
	likes_count: 321,
	attachments_uri: null,
	bpm: null,
	key_signature: null,
	user_favorite: null,
	user_playback_count: null,
	video_url: null,
	id: 218644653,
	kind: "track",
	created_at: "2015/08/10 20:10:00 +0000",
	last_modified: "2015/08/10 20:10:09 +0000",
	permalink: "04-how-we-be-peaking-lights-dub-mix",
	permalink_url: "https://soundcloud.com/dfa-records/04-how-we-be-peaking-lights-dub-mix",
	title: "04 How We Be (Peaking Lights Dub Mix)",
	duration: 521400,
	sharing: "public",
	waveform_url: "https://wis.sndcdn.com/5yaJuBh2AJq4_m.json",
	stream_url: "https://api.soundcloud.com/tracks/218644653/stream",
	uri: "https://api.soundcloud.com/tracks/218644653",
	user_id: 1520490,
	user_uri: "https://api.soundcloud.com/users/1520490",
	policy: "ALLOW",
	monetization_model: "NOT_APPLICABLE"
	},
	{
		artwork_url: "https://i1.sndcdn.com/artworks-000125950591-eqo688-large.jpg",
comment_count: 0,
commentable: true,
description: "",
download_count: 0,
downloadable: false,
embeddable_by: "all",
favoritings_count: 177,
genre: "DFA",
isrc: null,
label_id: null,
label_name: null,
license: "all-rights-reserved",
original_content_size: 20461946,
original_format: "mp3",
playback_count: 8787,
purchase_title: null,
purchase_url: null,
release: null,
release_day: null,
release_month: null,
release_year: null,
reposts_count: 11,
state: "finished",
streamable: true,
tag_list: "",
track_type: null,
user: {
avatar_url: "https://i1.sndcdn.com/avatars-000154063588-09fh4i-large.jpg",
id: 1520490,
kind: "user",
permalink_url: "http://soundcloud.com/dfa-records",
uri: "https://api.soundcloud.com/users/1520490",
username: "DFA Records",
permalink: "dfa-records",
last_modified: "2015/08/17 15:49:27 +0000"
},
likes_count: 177,
attachments_uri: null,
bpm: null,
key_signature: null,
user_favorite: null,
user_playback_count: null,
video_url: null,
id: 218644626,
kind: "track",
created_at: "2015/08/10 20:09:52 +0000",
last_modified: "2015/08/10 20:09:54 +0000",
permalink: "03-galley-boys-peaking-lights-dub-mix",
permalink_url: "https://soundcloud.com/dfa-records/03-galley-boys-peaking-lights-dub-mix",
title: "03 Galley Boys (Peaking Lights Dub Mix)",
duration: 443809,
sharing: "public",
waveform_url: "https://wis.sndcdn.com/mHkxquTckM6Z_m.json",
stream_url: "https://api.soundcloud.com/tracks/218644626/stream",
uri: "https://api.soundcloud.com/tracks/218644626",
user_id: 1520490,
user_uri: "https://api.soundcloud.com/users/1520490",
policy: "ALLOW",
monetization_model: "NOT_APPLICABLE"
},
{
	artwork_url: "https://i1.sndcdn.com/artworks-000125950601-ux147q-large.jpg",
comment_count: 1,
commentable: true,
description: "",
download_count: 0,
downloadable: false,
embeddable_by: "all",
favoritings_count: 224,
genre: "DFA",
isrc: null,
label_id: null,
label_name: null,
license: "all-rights-reserved",
original_content_size: 28390632,
original_format: "mp3",
playback_count: 10376,
purchase_title: null,
purchase_url: null,
release: null,
release_day: null,
release_month: null,
release_year: null,
reposts_count: 14,
state: "finished",
streamable: true,
tag_list: "",
track_type: null,
user: {
avatar_url: "https://i1.sndcdn.com/avatars-000154063588-09fh4i-large.jpg",
id: 1520490,
kind: "user",
permalink_url: "http://soundcloud.com/dfa-records",
uri: "https://api.soundcloud.com/users/1520490",
username: "DFA Records",
permalink: "dfa-records",
last_modified: "2015/08/17 15:49:27 +0000"
},
likes_count: 224,
attachments_uri: null,
bpm: null,
key_signature: null,
user_favorite: null,
user_playback_count: null,
video_url: null,
id: 218644593,
kind: "track",
created_at: "2015/08/10 20:09:41 +0000",
last_modified: "2015/08/10 20:09:58 +0000",
permalink: "02-yacha-peaking-lights-dub-mix",
permalink_url: "https://soundcloud.com/dfa-records/02-yacha-peaking-lights-dub-mix",
title: "02 Yacha (Peaking Lights Dub Mix)",
duration: 642045,
sharing: "public",
waveform_url: "https://wis.sndcdn.com/lQejtGTjQ3jL_m.json",
stream_url: "https://api.soundcloud.com/tracks/218644593/stream",
uri: "https://api.soundcloud.com/tracks/218644593",
user_id: 1520490,
user_uri: "https://api.soundcloud.com/users/1520490",
policy: "ALLOW",
monetization_model: "NOT_APPLICABLE"
}, {
	artwork_url: "https://i1.sndcdn.com/artworks-000089813370-dauwbi-large.jpg",
comment_count: 34,
commentable: true,
description: "Pop that Xanie. Free. @doja-cat",
download_count: 100,
downloadable: false,
embeddable_by: "all",
favoritings_count: 2556,
genre: "meeeoowww",
isrc: null,
label_id: null,
label_name: null,
license: "all-rights-reserved",
original_content_size: 67580844,
original_format: "wav",
playback_count: 66908,
purchase_title: null,
purchase_url: null,
release: null,
release_day: null,
release_month: null,
release_year: null,
reposts_count: 738,
state: "finished",
streamable: true,
tag_list: "",
track_type: null,
user: {
avatar_url: "https://i1.sndcdn.com/avatars-000134438722-mq7yd8-large.jpg",
id: 10558952,
kind: "user",
permalink_url: "http://soundcloud.com/djunderbelly",
uri: "https://api.soundcloud.com/users/10558952",
username: "UNDERBELLY",
permalink: "djunderbelly",
last_modified: "2015/08/17 16:29:22 +0000"
},
likes_count: 2556,
attachments_uri: null,
bpm: null,
key_signature: null,
user_favorite: null,
user_playback_count: null,
video_url: null,
id: 165834287,
kind: "track",
created_at: "2014/09/02 02:57:18 +0000",
last_modified: "2015/08/01 06:36:39 +0000",
permalink: "doja-cat-no-police-underbelly-bootleg",
permalink_url: "https://soundcloud.com/djunderbelly/doja-cat-no-police-underbelly-bootleg",
title: "Doja Cat - No Police (Underbelly Bootleg)",
duration: 191626,
sharing: "public",
waveform_url: "https://wis.sndcdn.com/vgHhCTxAKSoq_m.json",
stream_url: "https://api.soundcloud.com/tracks/165834287/stream",
uri: "https://api.soundcloud.com/tracks/165834287",
user_id: 10558952,
user_uri: "https://api.soundcloud.com/users/10558952",
policy: "ALLOW",
monetization_model: "NOT_APPLICABLE"
}
]
